### ISSUE TITLE
if $cached_name is the same as the $compiled name, should not regenerate

### ISSUE THREAD

**Issue by bechold** [wikimedia/less.php#94] opened 2023-03-08 09:32 UTC
In Less_Cache (Cache.php) ~line 83

if ( !$cached_name || $cached_name **===** $compiled_name )

should that not be 

if ( !$cached_name || $cached_name **!==** $compiled_name )  (cached_name NOT= $compiled_name)

**Comment by Krinkle** [comment] 2023-07-03 16:57
The condition in question, is for the case where we can return early for a cache hit.

The case where there is a cache miss, and we re-generate, is further down. I believe this is working as intended.

If you can find a case where, after modifying the input files, the next run wrongly returns a cache hit, or where without modifying the input, it is unnecessarily regenerating the output, feel free to comment below or create a new issue. I'll close this for now. Thanks!

**Closed by Krinkle** 2023-07-03 16:57 UTC
