### ISSUE TITLE
@container queries support?

### ISSUE THREAD

**Issue by melcak** [wikimedia/less.php#97] opened 2023-06-26 12:04 UTC
Hello, would be possilbe to add support for @container queries like:

`@container (max-width: 650px) { ... }`

Right now it throws: **Fatal error: Uncaught Less_Exception_Chunk: ParseError: Unexpected input**

**Comment by Gappa** [comment] 2023-06-28 05:28
Discussed/explained here: https://github.com/wikimedia/less.php/issues/91#issuecomment-1440260767

**Comment by Krinkle** [comment] 2023-09-09 19:48
Duplicate of https://github.com/wikimedia/less.php/issues/91.

**Closed by Krinkle** 2023-09-09 19:48 UTC
Labels: declined
